---
- name: Gather VPC Facts
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts
  
- name: Gather Subnet Facts
  ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_facts.vpcs[0].id }}"
      "tag:use": private
  register: subnet_facts